version: '3.8'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fixerpro

  redis:
    image: redis
    ports:
      - "6379:6379"